// القيم الافتراضية لإعدادات المتجر — أي حاجة مش متسجلة بتاخد القيمة دي
module.exports = {
  theme: {
    preset: "classic",
    accent: "#121212",
    accentText: "#ffffff",
    ink: "#121212",
    background: "#ffffff",
    soft: "#f5f5f4",
    sale: "#c0392b",
    font: "Inter",
    headingFont: "Inter",
    radius: 12,
    buttonShape: "pill",
    cardRatio: "portrait",
    cardStyle: "clean",
    cardHoverImage: true,
    showQuickAdd: true,
  },
  announcement: {
    enabled: true,
    messages: ["Free delivery on orders over EGP 3,000", "Cash on delivery available all over Egypt"],
    messagesAr: ["شحن مجاني للطلبات فوق 3,000 جنيه", "الدفع عند الاستلام متاح في كل مصر"],
    background: "#121212",
    color: "#ffffff",
    link: "",
    mode: "rotate",
  },
  header: {
    layout: "left",
    sticky: true,
    transparentOnHome: false,
    logoText: "بيت الذوق",
    logoImage: "",
    logoHeight: 44,
    showSearch: true,
    menu: [
      { label: "Home", labelAr: "الرئيسية", link: "/" },
      { label: "Shop", labelAr: "المتجر", link: "/products" },
      { label: "Categories", labelAr: "الأقسام", link: "/categories" },
      { label: "Sale", labelAr: "العروض", link: "/collections/sale" },
    ],
  },
  footer: {
    style: "dark",
    about: "Your trusted destination for elegant home essentials and modern home décor.",
    aboutAr: "وجهتك الموثوقة لمستلزمات البيت الأنيقة والديكور الحديث.",
    phone: "",
    email: "",
    address: "Cairo, Egypt",
    addressAr: "القاهرة، مصر",
    facebook: "",
    instagram: "",
    tiktok: "",
    whatsapp: "",
    showNewsletter: true,
    copyright: "بيت الذوق. All rights reserved.",
    copyrightAr: "بيت الذوق. جميع الحقوق محفوظة.",
  },
  language: {
    default: "ar",
    switcher: true,
    fontAr: "Cairo",
  },
  checkout: {
    codEnabled: true,
    codFee: 0,
    paypalEnabled: true,
    shippingFee: 60,
    freeShippingOver: 3000,
    guestCheckout: true,
    note: "",
  },
};
